flowchart LR
    n_rect[Rectangle]
    n_round(Round edges)
    n_stadium([Stadium])
    n_sub[[Subroutine]]
    n_cyl[(Cylinder)]
    n_circle((Circle))
    n_asym>Asymmetric]
    n_diamond{Diamond}
    n_hex{{Hexagon}}
    n_lean_r[/Lean right/]
    n_lean_l[\Lean left\]
    n_trap[/Trapezoid\]
    n_trap_alt[\Trapezoid alt/]
    n_dbl(((Double circle)))
