flowchart LR
    A --> B --> C --> D --> E
    linkStyle 0 stroke:#f00,stroke-width:3px
    linkStyle 1 stroke:#0a0,stroke-width:2px,stroke-dasharray:4 2
    linkStyle 2,3 stroke:#00f
    linkStyle default stroke:#999
