#include "Emitter.hpp"

#include <cctype>
#include <fstream>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace lrgen {
namespace {

std::string sanitize(const std::string &name) {
  if (name == kEndSymbol) return "End";
  std::string r;
  for (char c : name) r += (std::isalnum((unsigned char)c) || c == '_') ? c : '_';
  if (!r.empty() && std::isdigit((unsigned char)r[0])) r = "_" + r;
  return r;
}

// Distinct semantic types across all symbols, in first-appearance order.
std::vector<std::string> value_types(const Grammar &g) {
  std::vector<std::string> out;
  std::set<std::string> seen;
  for (const Symbol &s : g.symbols)
    if (s.type && seen.insert(*s.type).second) out.push_back(*s.type);
  return out;
}

// Replace $k with std::get<Tk>(std::move(rhs[k-1])) using RHS symbol types.
std::string substitute(const Grammar &g, const Production &p) {
  const std::string &a = p.action;
  std::string out;
  for (size_t i = 0; i < a.size();) {
    if (a[i] == '$' && i + 1 < a.size() && std::isdigit((unsigned char)a[i + 1])) {
      size_t j = i + 1;
      int k = 0;
      while (j < a.size() && std::isdigit((unsigned char)a[j])) {
        k = k * 10 + (a[j] - '0');
        ++j;
      }
      const std::string &type = *g.symbols[p.rhs[k - 1]].type;
      out += "std::get<" + type + ">(std::move(rhs[" + std::to_string(k - 1) + "]))";
      i = j;
    } else {
      out += a[i++];
    }
  }
  return out;
}

void write_file(const std::string &path, const std::string &content) {
  std::ofstream f(path);
  if (!f) throw std::runtime_error("cannot write " + path);
  f << content;
}

} // namespace

void emit(const Grammar &g, const std::vector<State> &states, const Tables &t,
          const std::string &out_base, const std::string &header_name) {
  const int nS = (int)states.size();
  const int nT = g.num_terminals();
  const int nN = g.num_nonterminals();
  const int nP = (int)g.productions.size();
  const std::string &ns = g.nspace;
  const std::string start_type = *g.symbols[g.start_sym].type;
  const int end_col = g.term_col[g.end_sym];

  // ── header ────────────────────────────────────────────────────────────
  {
    std::ostringstream h;
    h << "// GENERATED by lrgen — DO NOT EDIT.\n#pragma once\n\n";
    for (const std::string &inc : g.includes) h << "#include \"" << inc << "\"\n";
    h << "#include <optional>\n#include <string>\n#include <variant>\n"
         "#include <vector>\n\n";
    h << "namespace " << ns << " {\nusing namespace " << ns << "::ast;\n\n";

    h << "using Value = std::variant<std::monostate";
    for (const std::string &ty : value_types(g)) h << ", " << ty;
    h << ">;\n\n";

    h << "enum class Terminal : int {\n";
    for (int sym : g.terminals)
      h << "  " << sanitize(g.symbols[sym].name) << " = " << g.term_col[sym] << ",\n";
    h << "};\n\n";

    h << "struct Lexeme { Terminal sym; Value value; };\n\n";
    h << "struct ParseResult {\n"
         "  std::optional<" << start_type << "> value;\n"
         "  std::vector<std::string> errors;\n"
         "  bool ok = false;\n};\n\n";
    h << "ParseResult parse(std::vector<Lexeme> input);\n\n";
    h << "} // namespace " << ns << "\n";
    write_file(out_base + ".hpp", h.str());
  }

  // ── implementation ────────────────────────────────────────────────────
  {
    std::ostringstream c;
    c << "// GENERATED by lrgen — DO NOT EDIT.\n";
    c << "#include \"" << header_name << "\"\n";
    c << "#include <string>\n#include <utility>\n\n";
    c << "namespace " << ns << " {\nnamespace {\n\n";

    c << "struct Action { unsigned char kind; int arg; }; // 0 err 1 shift 2 reduce 3 accept\n";
    c << "struct ProdInfo { int lhs_nt; int rhs_len; };\n\n";
    c << "constexpr int kEndCol = " << end_col << ";\n\n";

    // ACTION table
    c << "const Action kAction[" << nS << "][" << nT << "] = {\n";
    for (int s = 0; s < nS; ++s) {
      c << "  {";
      for (int col = 0; col < nT; ++col) {
        const LRAction &a = t.action[s][col];
        int k = a.kind; // Error=0 Shift=1 Reduce=2 Accept=3 (matches LRAction::Kind)
        c << "{" << k << "," << a.arg << "}" << (col + 1 < nT ? "," : "");
      }
      c << "},\n";
    }
    c << "};\n\n";

    // GOTO table
    c << "const int kGoto[" << nS << "][" << nN << "] = {\n";
    for (int s = 0; s < nS; ++s) {
      c << "  {";
      for (int col = 0; col < nN; ++col)
        c << t.go[s][col] << (col + 1 < nN ? "," : "");
      c << "},\n";
    }
    c << "};\n\n";

    // production info
    c << "const ProdInfo kProd[" << nP << "] = {\n";
    for (const Production &p : g.productions)
      c << "  {" << g.nt_col[p.lhs] << "," << (int)p.rhs.size() << "},\n";
    c << "};\n\n";

    // terminal names (diagnostics)
    c << "const char* const kTermName[" << nT << "] = {";
    for (int i = 0; i < nT; ++i)
      c << "\"" << g.symbols[g.terminals[i]].name << "\"" << (i + 1 < nT ? "," : "");
    c << "};\n\n";

    // reduce actions
    c << "Value reduce_action(int prod, Value* rhs) {\n  (void)rhs;\n  switch (prod) {\n";
    for (int p = 1; p < nP; ++p) {
      const Production &P = g.productions[p];
      if (P.action.empty())
        throw std::runtime_error("production " + std::to_string(p) +
                                 " (line " + std::to_string(P.line) +
                                 ") has no action");
      c << "    case " << p << ": return Value{ " << substitute(g, P) << " };\n";
    }
    c << "    default: return Value{};\n  }\n}\n\n";

    c << "} // anonymous namespace\n\n";

    // the driver
    c << "ParseResult parse(std::vector<Lexeme> input) {\n"
         "  std::vector<int> states{0};\n"
         "  std::vector<Value> values;\n"
         "  std::size_t ip = 0;\n"
         "  for (;;) {\n"
         "    int st = states.back();\n"
         "    int col = (ip < input.size()) ? (int)input[ip].sym : kEndCol;\n"
         "    Action a = kAction[st][col];\n"
         "    if (a.kind == 1) { // shift\n"
         "      states.push_back(a.arg);\n"
         "      values.push_back(std::move(input[ip].value));\n"
         "      ++ip;\n"
         "    } else if (a.kind == 2) { // reduce\n"
         "      const ProdInfo& p = kProd[a.arg];\n"
         "      Value v = reduce_action(a.arg, values.data() + (values.size() - p.rhs_len));\n"
         "      states.resize(states.size() - p.rhs_len);\n"
         "      values.resize(values.size() - p.rhs_len);\n"
         "      values.push_back(std::move(v));\n"
         "      states.push_back(kGoto[states.back()][p.lhs_nt]);\n"
         "    } else if (a.kind == 3) { // accept\n"
         "      return ParseResult{ std::get<" << start_type << ">(std::move(values.back())), {}, true };\n"
         "    } else { // error\n"
         "      return ParseResult{ std::nullopt,\n"
         "        { std::string(\"syntax error at input \") + std::to_string(ip) +\n"
         "          \" near terminal '\" + kTermName[col] + \"'\" }, false };\n"
         "    }\n"
         "  }\n}\n\n";

    c << "} // namespace " << ns << "\n";
    write_file(out_base + ".cpp", c.str());
  }
}

} // namespace lrgen
