#pragma once

#include "mermaid/FlowDb.hpp"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <string>
#include <vector>

// Canonicalizes both our FlowDb and an extract.mjs .ast.json into the same JSON
// shape, so nlohmann's json::operator== is a correct structural comparison and
// its pretty-printer gives a readable diff.
//
// The .ast.json golden files are generated by mermaid-utils/extract.mjs; see
// that directory's README ("Generating fixtures for the C++ verification suite")
// for how to add/regenerate a fixture.
//
// Normalization:
//   * enums -> mermaid's strings (pinned against extract.mjs probes),
//   * drop non-portable fields (domId, edge id/index) and deferred ones
//     (tooltip/link),
//   * vertices/subgraphs/classes keyed by id (order-independent),
//   * edges as an ordered array (linkStyle index), set-valued fields sorted.

namespace mermaid::fixture {

using json = nlohmann::json;

inline std::string dir_str(Direction d) {
  switch (d) {
  case Direction::TB: return "TB";
  case Direction::BT: return "BT";
  case Direction::LR: return "LR";
  case Direction::RL: return "RL";
  }
  return "?";
}

// Bare nodes are "rect"; explicit [text] is "square" (see Vertex::explicit_shape).
inline std::string shape_str(ShapeKind s, bool explicit_shape) {
  if (!explicit_shape) return "rect";
  switch (s) {
  case ShapeKind::Rect: return "square";
  case ShapeKind::RoundEdges: return "round";
  case ShapeKind::Stadium: return "stadium";
  case ShapeKind::Subroutine: return "subroutine";
  case ShapeKind::Cylinder: return "cylinder";
  case ShapeKind::Circle: return "circle";
  case ShapeKind::Asymmetric: return "odd";
  case ShapeKind::Rhombus: return "diamond";
  case ShapeKind::Hexagon: return "hexagon";
  case ShapeKind::LeanRight: return "lean_right";
  case ShapeKind::LeanLeft: return "lean_left";
  case ShapeKind::Trapezoid: return "trapezoid";
  case ShapeKind::TrapezoidAlt: return "inv_trapezoid";
  case ShapeKind::DoubleCircle: return "doublecircle";
  }
  return "?";
}

inline std::string stroke_str(Stroke s) {
  switch (s) {
  case Stroke::Normal: return "normal";
  case Stroke::Thick: return "thick";
  case Stroke::Dotted: return "dotted";
  case Stroke::Invisible: return "invisible";
  }
  return "?";
}

// mermaid folds bidirectionality into the arrowHead string only for arrows.
inline std::string arrowhead_str(ArrowHead h, bool head_start) {
  switch (h) {
  case ArrowHead::None: return "arrow_open";
  case ArrowHead::Arrow: return head_start ? "double_arrow_point" : "arrow_point";
  case ArrowHead::Circle: return "arrow_circle";
  case ArrowHead::Cross: return "arrow_cross";
  }
  return "?";
}

inline std::vector<std::string> sorted(std::vector<std::string> v) {
  std::sort(v.begin(), v.end());
  return v;
}

// ── FlowDb -> canonical json ────────────────────────────────────────────────
inline json canonical(const FlowDb &db) {
  json vertices = json::object();
  for (const Vertex &v : db.vertices)
    vertices[v.id] = {{"label", v.label},
                      {"shape", shape_str(v.shape, v.explicit_shape)},
                      {"classes", sorted(v.classes)},
                      {"styles", v.styles}};

  json edges = json::array();
  for (const Edge &e : db.edges)
    edges.push_back({{"start", e.start},
                     {"end", e.end},
                     {"label", e.label},
                     {"stroke", stroke_str(e.stroke)},
                     {"arrowHead", arrowhead_str(e.head_end, e.head_start)},
                     {"length", e.length}});

  json subgraphs = json::object();
  for (const Subgraph &s : db.subgraphs)
    subgraphs[s.id] = {{"label", s.label},
                       {"nodes", sorted(s.nodes)},
                       {"direction", s.dir ? json(dir_str(*s.dir)) : json(nullptr)}};

  json classes = json::object();
  for (const auto &[name, def] : db.classes)
    classes[name] = {{"styles", def.styles}};

  return {{"direction", dir_str(db.direction)},
          {"vertices", vertices},
          {"edges", edges},
          {"subgraphs", subgraphs},
          {"classes", classes}};
}

// ── extract .ast.json -> same canonical json ────────────────────────────────
inline std::string as_str(const json &j) { return j.is_null() ? "" : j.get<std::string>(); }
inline std::vector<std::string> as_vec(const json &j) {
  return j.is_null() ? std::vector<std::string>{} : j.get<std::vector<std::string>>();
}

inline json canonical_extract(const json &raw) {
  json vertices = json::object();
  for (const json &v : raw.at("vertices"))
    vertices[v.at("id").get<std::string>()] = {
        {"label", as_str(v.at("label"))},
        {"shape", v.at("shape")},
        {"classes", sorted(as_vec(v.value("classes", json::array())))},
        {"styles", as_vec(v.value("styles", json::array()))}};

  json edges = json::array();
  for (const json &e : raw.at("edges"))
    edges.push_back({{"start", e.at("start")},
                     {"end", e.at("end")},
                     {"label", as_str(e.value("label", json()))},
                     {"stroke", e.at("stroke")},
                     {"arrowHead", e.at("arrowHead")},
                     {"length", e.at("length")}});

  json subgraphs = json::object();
  for (const json &s : raw.at("subgraphs"))
    subgraphs[s.at("id").get<std::string>()] = {
        {"label", as_str(s.at("label"))},
        {"nodes", sorted(as_vec(s.value("nodes", json::array())))},
        {"direction", s.at("direction").is_null() ? json(nullptr) : s.at("direction")}};

  json classes = json::object();
  for (auto it = raw.at("classes").begin(); it != raw.at("classes").end(); ++it)
    classes[it.key()] = {{"styles", as_vec(it.value().value("styles", json::array()))}};

  return {{"direction", raw.at("direction")},
          {"vertices", vertices},
          {"edges", edges},
          {"subgraphs", subgraphs},
          {"classes", classes}};
}

} // namespace mermaid::fixture
